-- MySQL Script generated by MySQL Workbench
-- Sat Sep 24 01:02:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jakes_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jakes_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jakes_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `jakes_db` ;

-- -----------------------------------------------------
-- Table `jakes_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakes_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birth_date` DATETIME NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jakes_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakes_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `users_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_workout_categories_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_workout_categories_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `jakes_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jakes_db`.`workouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakes_db`.`workouts` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `quantity` DOUBLE NOT NULL,
  `measurement` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NULL,
  `users_id` INT NULL,
  `workout_categories_id` INT NULL,
  `dynamic_attributes` JSON NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_workouts_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_workouts_workout_categories1_idx` (`workout_categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_workouts_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `jakes_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workouts_workout_categories1`
    FOREIGN KEY (`workout_categories_id`)
    REFERENCES `jakes_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jakes_db`.`workout_plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakes_db`.`workout_plans` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NULL,
  `users_id` INT NULL,
  `categories_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_workout_plans_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_workout_plans_categories1_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_workout_plans_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `jakes_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workout_plans_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `jakes_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jakes_db`.`user_weight_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakes_db`.`user_weight_records` (
  `id` INT NOT NULL,
  `weight` DOUBLE NULL,
  `date` DATETIME NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_weight_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_weight_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `jakes_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jakes_db`.`user_height_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakes_db`.`user_height_records` (
  `id` INT NOT NULL,
  `height` DOUBLE NULL,
  `date` DATETIME NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_weight_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_weight_users10`
    FOREIGN KEY (`users_id`)
    REFERENCES `jakes_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jakes_db`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jakes_db`.`events` (
  `id` INT NOT NULL,
  `date` DATETIME NULL,
  `workout_plans_id` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_workout_plans1_idx` (`workout_plans_id` ASC) VISIBLE,
  INDEX `fk_events_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_events_workout_plans1`
    FOREIGN KEY (`workout_plans_id`)
    REFERENCES `jakes_db`.`workout_plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `jakes_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
